# A github action for building archival sites and publishing them to a branch.
name: Build & Publish Archival Site
author: "Archival Team"
branding:
  icon: "archive"
  color: "green"
inputs:
  token:
    description: "github token to use. Typically secrets.GITHUB_TOKEN"
    required: true
  branch:
    description: "branch to write output to"
    required: false
    default: "archival-dist"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
    - name: Set Build Dir
      id: dist
      run: echo "dist=\"$(bin/archival manifest build-dir)\"" >> $GITHUB_OUTPUT
      shell: bash
    - name: Archival Prebuild
      run: bin/archival prebuild
      shell: bash
    - name: Build with Archival
      run: bin/archival build
      shell: bash
    - name: Deploy
      uses: s0/git-publish-subdir-action@v2.6.0
      env:
        REPO: self
        BRANCH: ${{ inputs.branch }}
        FOLDER: ${{ steps.dist.outputs.dist }}
        GITHUB_TOKEN: ${{ inputs.token }}
