[package]
name = "archival"
version = "0.3.0"
edition = "2021"
license = "Unlicense"
description = "The simplest CMS in existence"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "archival"
path = "src/lib.rs"

[features]
default = ["binary"]
typescript = ["dep:typescript-type-def"]
binary = ["dep:ctrlc", "stdlib-fs"]
stdlib-fs = ["dep:notify", "dep:fs_extra", "dep:walkdir"]
wasm-fs = [
    "dep:wasm-bindgen",
    "dep:web-sys",
    "dep:wasm-bindgen-futures",
    "dep:indexed_db_futures",
    "dep:serde-wasm-bindgen",
    "time/wasm-bindgen",
]

[[bin]]
name = "archival"
path = "src/main.rs"

## Eventually:
## https://github.com/rust-lang/cargo/issues/1197
# [target.'cfg(target_arch = "wasm32")'.features]
# default = ["wasm-fs"]
# [target.'cfg(not(target_arch = "wasm32"))'.features]
# default = ["stdlib-fs", "binary"]

[dependencies]
# stdlib-fs
walkdir = { version = "2.3.3", optional = true }
fs_extra = { version = "1.3.0", optional = true }
notify = { version = "6.1.1", optional = true }
ctrlc = { version = "3.4.2", optional = true }
futures = { version = "0.3.30", features = ["executor"] }
# wasm-fs
wasm-bindgen = { version = "0.2.87", features = [
    "serde-serialize",
], optional = true }
web-sys = { version = "0.3.66", optional = true, features = [
    "IdbKeyRange",
    "DomException",
] }
wasm-bindgen-futures = { version = "0.4.37", optional = true }
serde-wasm-bindgen = { version = "0.4", optional = true }
indexed_db_futures = { version = "0.3.0", optional = true }
serde_bytes = "0.11.12"
typescript-type-def = { version = "0.5.9", optional = true }
# shared
liquid = "0.26.1"
serde = "1.0.152"
toml = { version = "0.7.1", features = ["display"] }
comrak = "0.18"
liquid-core = "0.26.4"
liquid-lib = { version = "0.26.4", features = ["shopify", "extra"] }
regex = "1.10.2"
thiserror = "1.0.56"
zip = { version = "0.6.6", default_features = false, features = ["deflate"] }
toml_datetime = "0.6.5"
tracing = "0.1.37"
time = { version = "0.3.31", features = ["local-offset"] }

[dev-dependencies]
rand = "0.8.5"
serde_json = "1.0.113"
tempfile = "3.5.0"
tracing-test = "0.2.4"
wasm-bindgen-test = "0.3.0"
