[package]
name = "archival"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "archival"
path = "src/lib.rs"

[[bin]]
name = "archival"
path = "src/main.rs"

[dependencies]
liquid = "0.26.1"
serde = "1.0.152"
toml = "0.7.1"
walkdir = "2.3.3"
comrak = "0.18"
liquid-core = "0.26.4"
liquid-lib = { version = "0.26.4", features = ["shopify", "extra"] }
regex = "1.10.2"
fs_extra = "1.3.0"
notify = "6.1.1"
ctrlc = "3.4.2"

[dev-dependencies]
tempfile = "3.5.0"
