[package]
name = "archival-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "archival"
path = "src/lib.rs"

[dependencies]
liquid = "0.26.1"
serde = "1.0.152"
toml = "0.7.1"
walkdir = "2.3.3"

[dev-dependencies]
tempfile = "3.5.0"
